import * as fs from 'fs'
import * as path from 'path'
import { IndustryData, ServiceSpec } from '../lib/industry-loader'
import { slugify } from '../lib/utils'

const INDUSTRIES_DIR = path.join(process.cwd(), 'industries')

export async function generateIndustryTool(industry: IndustryData): Promise<void> {
  const industryDir = path.join(INDUSTRIES_DIR, industry.slug)

  // Create industry directory
  if (!fs.existsSync(industryDir)) {
    fs.mkdirSync(industryDir, { recursive: true })
  }

  const service = industry.documentation?.services?.[0]

  // Generate files
  await Promise.all([
    generateReadme(industryDir, industry, service),
    generatePackageJson(industryDir, industry),
    generateAppPage(industryDir, industry, service),
    generateDemoPage(industryDir, industry, service),
    generateComponents(industryDir, industry, service),
    generateApiRoutes(industryDir, industry, service),
    generateLib(industryDir, industry, service),
  ])

  console.log(`Generated: ${industry.slug}`)
}

async function generateReadme(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const content = `# ${industry.idea}

## ${industry.industry}

${industry.oneLineSummary}

## Problem Solved

${industry.problemItSolves}

## Core Solution

${industry.coreSolution}

## Target Users

${industry.targetUsers}

## Business Impact

${industry.businessImpact}

## Example Use Case

${industry.exampleUseCase}

${service ? `
## Features

${service.core_features.map(f => `- ${f}`).join('\n')}

## AI Capabilities

${service.ai_capabilities.map(c => `- ${c}`).join('\n')}

## Technical Stack

- **Frontend**: ${service.technical_specifications?.recommended_tech_stack?.frontend || 'Next.js'}
- **Backend**: ${service.technical_specifications?.recommended_tech_stack?.backend || 'Node.js'}
- **Database**: ${service.technical_specifications?.recommended_tech_stack?.database || 'PostgreSQL'}
- **AI**: ${service.technical_specifications?.recommended_tech_stack?.AI || 'OpenAI API'}

## API Endpoints

${service.technical_specifications?.API_design?.map(api => `\`\`\`\n${api}\n\`\`\``).join('\n\n') || 'See documentation'}

## Success Metrics

${service.success_metrics?.map(m => `- ${m}`).join('\n') || 'See documentation'}
` : ''}

---

Generated by AI Digital Services Pipeline
`

  fs.writeFileSync(path.join(dir, 'README.md'), content)
}

async function generatePackageJson(dir: string, industry: IndustryData): Promise<void> {
  const content = {
    name: `@ai-digital-services/${industry.slug}`,
    version: '1.0.0',
    description: industry.oneLineSummary,
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
    },
    dependencies: {
      next: '^14.0.0',
      react: '^18.2.0',
      'react-dom': '^18.2.0',
    },
  }

  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(content, null, 2))
}

async function generateAppPage(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const appDir = path.join(dir, 'app')
  if (!fs.existsSync(appDir)) {
    fs.mkdirSync(appDir, { recursive: true })
  }

  const content = `import Link from 'next/link'

export const metadata = {
  title: '${industry.idea} | ${industry.industry}',
  description: '${industry.oneLineSummary.replace(/'/g, "\\'")}',
}

export default function HomePage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white">
      <div className="max-w-7xl mx-auto px-4 py-16 sm:px-6 lg:px-8">
        {/* Hero */}
        <div className="text-center">
          <span className="inline-block px-3 py-1 text-sm font-medium bg-blue-100 text-blue-800 rounded-full mb-4">
            ${industry.industry}
          </span>
          <h1 className="text-4xl font-bold text-gray-900 sm:text-5xl md:text-6xl">
            ${industry.idea}
          </h1>
          <p className="mt-6 max-w-2xl mx-auto text-xl text-gray-500">
            ${industry.oneLineSummary}
          </p>
          <div className="mt-8 flex justify-center gap-4">
            <Link
              href="/demo"
              className="px-6 py-3 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition"
            >
              Try Demo
            </Link>
            <a
              href="/"
              className="px-6 py-3 border border-gray-300 font-semibold rounded-lg hover:bg-gray-50 transition"
            >
              Learn More
            </a>
          </div>
        </div>

        {/* Features */}
        <div className="mt-20">
          <h2 className="text-2xl font-bold text-center mb-12">Core Features</h2>
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            ${service?.core_features?.slice(0, 6).map((feature, i) => `
            <div className="p-6 bg-white rounded-xl border shadow-sm">
              <h3 className="font-semibold mb-2">Feature ${i + 1}</h3>
              <p className="text-gray-600 text-sm">${feature.split(':')[0]}</p>
            </div>`).join('') || `
            <div className="p-6 bg-white rounded-xl border shadow-sm">
              <p className="text-gray-600">AI-powered analysis</p>
            </div>
            <div className="p-6 bg-white rounded-xl border shadow-sm">
              <p className="text-gray-600">Real-time processing</p>
            </div>
            <div className="p-6 bg-white rounded-xl border shadow-sm">
              <p className="text-gray-600">Seamless integration</p>
            </div>`}
          </div>
        </div>

        {/* Problem & Solution */}
        <div className="mt-20 grid md:grid-cols-2 gap-12">
          <div>
            <h2 className="text-2xl font-bold mb-4">Problem</h2>
            <p className="text-gray-600">${industry.problemItSolves}</p>
          </div>
          <div>
            <h2 className="text-2xl font-bold mb-4">Solution</h2>
            <p className="text-gray-600">${industry.coreSolution}</p>
          </div>
        </div>

        {/* Use Case */}
        <div className="mt-20 bg-blue-50 rounded-2xl p-8">
          <h2 className="text-2xl font-bold mb-4">Example Use Case</h2>
          <p className="text-gray-700">${industry.exampleUseCase}</p>
        </div>

        {/* CTA */}
        <div className="mt-20 text-center">
          <h2 className="text-2xl font-bold mb-4">Ready to Get Started?</h2>
          <p className="text-gray-600 mb-8">Transform your ${industry.industry.toLowerCase()} operations with AI</p>
          <Link
            href="/demo"
            className="inline-block px-8 py-4 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 transition"
          >
            Try the Demo
          </Link>
        </div>
      </div>
    </div>
  )
}
`

  fs.writeFileSync(path.join(appDir, 'page.tsx'), content)

  // Create layout.tsx
  const layoutContent = `import './globals.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`

  fs.writeFileSync(path.join(appDir, 'layout.tsx'), layoutContent)

  // Create globals.css
  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;
`

  fs.writeFileSync(path.join(appDir, 'globals.css'), globalsCss)
}

async function generateDemoPage(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const demoDir = path.join(dir, 'app', 'demo')
  if (!fs.existsSync(demoDir)) {
    fs.mkdirSync(demoDir, { recursive: true })
  }

  const content = `'use client'

import { useState } from 'react'
import Link from 'next/link'

export default function DemoPage() {
  const [input, setInput] = useState('')
  const [response, setResponse] = useState('')
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!input.trim()) return

    setLoading(true)

    // Simulate AI response
    await new Promise(resolve => setTimeout(resolve, 1500))

    setResponse(\`Based on your input about "\${input}", our AI system would provide:

1. **Analysis**: Comprehensive evaluation of your query
2. **Recommendations**: Actionable insights specific to ${industry.industry}
3. **Next Steps**: Clear guidance for implementation

This is a demonstration. Contact us for full functionality.\`)

    setLoading(false)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12">
      <div className="max-w-4xl mx-auto px-4">
        <Link href="/" className="text-blue-600 hover:underline mb-8 inline-block">
          ← Back to Home
        </Link>

        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold">${industry.idea}</h1>
          <p className="text-gray-600 mt-2">Interactive Demo</p>
        </div>

        <div className="bg-white rounded-xl shadow-sm border overflow-hidden">
          <div className="min-h-[300px] p-6 bg-gray-50">
            {!response && !loading && (
              <div className="text-center text-gray-500">
                Enter your query below to see the AI in action
              </div>
            )}
            {loading && (
              <div className="text-center">
                <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto"></div>
                <p className="mt-4 text-gray-600">Processing...</p>
              </div>
            )}
            {response && !loading && (
              <div className="prose max-w-none">
                <div className="bg-gray-100 p-4 rounded-lg mb-4">
                  <strong>Your Query:</strong> {input}
                </div>
                <div className="bg-blue-50 p-4 rounded-lg whitespace-pre-wrap">
                  {response}
                </div>
              </div>
            )}
          </div>

          <form onSubmit={handleSubmit} className="border-t p-4 flex gap-4">
            <input
              type="text"
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Enter your query..."
              className="flex-1 px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
              disabled={loading}
            />
            <button
              type="submit"
              disabled={loading || !input.trim()}
              className="px-6 py-2 bg-blue-600 text-white font-semibold rounded-lg hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Processing...' : 'Submit'}
            </button>
          </form>
        </div>
      </div>
    </div>
  )
}
`

  fs.writeFileSync(path.join(demoDir, 'page.tsx'), content)
}

async function generateComponents(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const componentsDir = path.join(dir, 'components')
  if (!fs.existsSync(componentsDir)) {
    fs.mkdirSync(componentsDir, { recursive: true })
  }

  // Generate components based on frontend_components from spec
  const components = service?.technical_specifications?.frontend_components || []

  for (const componentSpec of components) {
    const componentName = componentSpec.split(':')[0].replace(/\s+/g, '')
    const fileName = `${componentName}.tsx`

    const content = `// Auto-generated component: ${componentName}
// Based on: ${componentSpec}

interface ${componentName}Props {
  className?: string
}

export function ${componentName}({ className }: ${componentName}Props) {
  return (
    <div className={className}>
      <p>${componentSpec}</p>
      {/* Implement component logic here */}
    </div>
  )
}
`

    fs.writeFileSync(path.join(componentsDir, fileName), content)
  }
}

async function generateApiRoutes(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const apiDir = path.join(dir, 'app', 'api', 'analyze')
  if (!fs.existsSync(apiDir)) {
    fs.mkdirSync(apiDir, { recursive: true })
  }

  const content = `import { NextRequest, NextResponse } from 'next/server'

// API route for ${industry.idea}
// Industry: ${industry.industry}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { input } = body

    if (!input) {
      return NextResponse.json({ error: 'Input required' }, { status: 400 })
    }

    // TODO: Implement AI logic
    // This would connect to OpenAI or your custom model

    const response = {
      success: true,
      analysis: \`Analysis for: \${input}\`,
      recommendations: [
        'Recommendation 1',
        'Recommendation 2',
        'Recommendation 3',
      ],
      confidence: 0.85,
    }

    return NextResponse.json(response)
  } catch (error) {
    return NextResponse.json({ error: 'Processing failed' }, { status: 500 })
  }
}

/*
API Design from specifications:
${service?.technical_specifications?.API_design?.join('\n') || 'No API specs provided'}
*/
`

  fs.writeFileSync(path.join(apiDir, 'route.ts'), content)
}

async function generateLib(dir: string, industry: IndustryData, service?: ServiceSpec): Promise<void> {
  const libDir = path.join(dir, 'lib')
  if (!fs.existsSync(libDir)) {
    fs.mkdirSync(libDir, { recursive: true })
  }

  const aiMockContent = `// AI Mock responses for ${industry.idea}
// Used for demos when no API key is configured

export function generateMockResponse(input: string): string {
  return \`
Based on your input regarding "${industry.industry}":

**Analysis Complete**

Our ${industry.idea} system has processed your request. Here's a summary:

1. **Input Received**: \${input}
2. **Processing**: Applied ${service?.ai_capabilities?.[0] || 'AI analysis'}
3. **Result**: Demo response generated

For production use, this would connect to:
${service?.integration_plan?.required_integrations?.slice(0, 3).map(i => `- ${i}`).join('\n') || '- External APIs\n- Data sources'}

Contact us to enable full AI capabilities.
\`
}

export const industryConfig = {
  name: '${industry.industry}',
  idea: '${industry.idea}',
  targetUsers: '${industry.targetUsers}',
  aiCapabilities: ${JSON.stringify(service?.ai_capabilities || [], null, 2)},
}
`

  fs.writeFileSync(path.join(libDir, 'ai-mock.ts'), aiMockContent)
}
